global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: 'go-ethereum'
  scrape_interval: 10s
  metrics_path: /debug/metrics/prometheus
  static_configs:
    - targets:
        - 'geth:6060'
      labels:
        chain: ethereum
# - job_name: prometheus
#   honor_timestamps: true
#   scrape_interval: 5s
#   scrape_timeout: 5s
#   metrics_path: /metrics
#   scheme: http
#   static_configs:
#   - targets:
#     - localhost:9090